### ISSUE TITLE
constexpr-fy cpp_double_float and cpp_quad_float

### ISSUE THREAD

**Issue by sinandredemption** [BoostGSoC21/multiprecision#37]
The purpose of creation of this issue is to track the places in `cpp_double_float/cpp_quad_float` where constexpr support is _theoretically_ possible but not implemented in practice yet, and to discuss such possible implementations.

Currently cpp_double_float doesn't support constexpr in the following cases:
- Construction from an integer which holds more information than cpp_double_float can contain
- `std::numeric_limits<>: min(), max(), epsilon()`

Please feel free to add more cases or to describe your proposals of implementation of constexpr in the mentioned cases.

**Comment by ckormanyos** [comment]
The `cpp_double_float` template class is expected to be rich in C++11 traditional `constexpr` opportunity. Since the members are but two built-in elements, not much looping takes place in constructors, limits and arithmetic ops. So, in fact, even a lot of old-school C++11 `constexpr` _should_ be possible.

In Boost.Math and Boost.Multiprecision, we differentiate between C++11 `constexpr` and C++14,17,20 and beyond. For the C++11 case, the actual word `constexpr` is used when possible and conformant with C++11. For later, more relaxed versions of constant expression-ness, we use existing Boost macros, the names of which I`ve forgotten at the moment.

**Comment by ckormanyos** [comment]
Integrate the `exact_arithmetic` helper class when ´constexpr`-ifying.

**Comment by ckormanyos** [comment]
In the post-GSoC phase, I intend to get the ball rolling on this issue. I do, however, really want to resolve #35 prior to beginning `constexpr`-fication, as this issue breaks numeric correctness and still remains open.

After all that, I think we would have a stable starting point for `constexpr`. In Boost as well as other projects, it has become common to differentiate between two forms of `constexpr`-ness: C++11 and C++14-and-beyond. Sinple stuff can be C++11 `constexpr` while it can be more convenient to use higher language standard(s) when compound subroutines with higher complexity are involved.

Boost has a macro for C++14 `constexpr`-ness and beyond. For C++11 `constexpr`-ness, we simply use the keyword `constexpr`.

**Comment by ckormanyos** [comment]
Preliminarily fixed for double-float only (as a prototype) in 494cde8994289bcda18c701d25543bf309cbaf54

Refinements of `constexpr`-ification are still needed. These will be handled in future issues as they arise.
