### ISSUE TITLE
cpp_quad_float<float> construction from string problems

### ISSUE THREAD

**Issue by sinandredemption** [BoostGSoC21/multiprecision#83]
As @ckormanyos and me have noticed, `cpp_quad_float<float>` default Boost constructor fails even with simple string parsing. The problematic lines have been identified as [lines 302-306](https://github.com/BoostGSoC21/multiprecision/blob/5955a26d63770f1e46e631574de2996f3a8e3ed4/include/boost/multiprecision/detail/float_string_cvt.hpp#L302) in file `float_string_cvt.hpp`.

One possible solution to this is relatively straightforward. Use the simple multiply-by-10 loop until the desired shift is reached. This has been previously done and it worked, albeit through a specialized string constructor which kind of goes against the philosophy of Boost-ification of the class.

Thoughts?
@ckormanyos @cosurgi

**Comment by ckormanyos** [comment]
> `cpp_quad_float<float>` default Boost constructor fails even with simple string parsing.

Aside from the short time remaining, I am slightly more concerned with the limited exponent range of `cpp_quad_float<float>` altogether. The thing basically overflows/underflows upon construction from 30 digit string itself. Consider the final fourth limb. Its Exponent (even for floating-point numbers of Order-0) will be down about 10^(-30), which is shockingly close to the minimum range of common 4-byte `float`

> One possible solution to this is relatively straightforward...

An even **more simple** solution: Don't deal with it at all. Part of me says, _Scrap_ `cpp_quad_float<float>` altogether. I can (with great fear and premonition) foresee 5 to 10 bug reports per year simply based on overflow/underflow of the type itself. It will hardly play with any of the stuff in Boost.Math.

We could think of creative upscaling/downscaling, but only with massive development effort. I'm not into that at the moment.

To me, I strongly recommend dealing with this post-GSoC21. Fahad, you have accomplished so much in this short time. It's getting on toward wrap-up/report time.

**Comment by sinandredemption** [comment]
>  Part of me says, Scrap cpp_quad_float<float> altogether.

I too do not feel like there would be much use for `cpp_quad_float<float>` aside from systems that lack a native `double`.

However, note that only the `min_exponent` of `cpp_quad_float<float>` is capped. So things that don't deal with extremely small numbers should theoretically be fine.

> We could think of creative upscaling/downscaling, but only with massive development effort. I'm not into that at the moment.

Yes, I have been thinking about similar things. But yeah, that stuff would definitely be _very_ post-GSoC, as IEEE-correct algorithms for `cpp_double_float` would personally be my priority.

> To me, I strongly recommend dealing with this post-GSoC21. Fahad, you have accomplished so much in this short time. It's getting on toward wrap-up/report time.

**Comment by ckormanyos** [comment]
>  much use for `cpp_quad_float<float>` aside from systems that lack a native double

Agreed. I think we should put this issue on lower priority and handle it later.

> as IEEE-correct algorithms for `cpp_double_float` would personally be my priority

That seems like  good idea.

**Comment by cosurgi** [comment]
> scrap `cpp_quad_float<float>` altogether. [……], but only with massive development effort. I'm not into that at the moment.

agreed. Solving a multi_float with maximum number of limbs (covering whole exponent range) is an entirely different challenge. Not a part of this GSoC.

**Comment by ckormanyos** [comment]
> agreed. Solving a multi_float with maximum number of limbs (covering whole exponent range) is an entirely different challenge. Not a part of this GSoC.

I lost track of one post in which Janek mentioned we might get a skeleton of tuned tests running for `cpp_quad_float<float>`. In addition to postponing the full effort on ranges (we all agree), I also agree with that suggestion. I can work out a set of passing  `cpp_quad_float<float>` as we progress, but rather commenting out non-passing tests instead of investing large amounts of time in them.

Cc: @sinandredemption and @cosurgi

**Comment by cosurgi** [comment]
It was this post: https://github.com/BoostGSoC21/multiprecision/pull/82#issuecomment-898889189

sorry for replying in different thread. It was the first one I saw today tackling this problem.

**Comment by sinandredemption** [comment]
Since we are planning on scrapping `cpp_quad_float<float>` (at least temporarily), how is this to be established? Via a `static_assert`? Mentioning in documentation?

@ckormanyos @cosurgi

**Comment by ckormanyos** [comment]
> how is this to be established? Via a `static_assert`? Mentioning in documentation?

Those sound like viable plans. I'm torn between a complete scratch via `static_assert` and getting some tiny subset of tests working and, let's say, rolling with it for a while.

The bottom-liner in me, however, tends to favor clarity above ambiguity, which would indicate from my side a slight preference for `static_assert`. Although we did mention leaving it active and making a few tests, I would, in light of moving fast, scrap via `static_assert´.

If you craft the `static_assert`, remember to test not only on the type `float`, but rather on the actual values of `min_exponent`/`max_exponent`. This is actually a valuable thought process. How to test for a quad-float constituent type (or to a lesser extent also a double-float constituent type) for adequate numeric range to be used? Test on exponent ranges or the type itself? I think the former, since that is the actual bottle neck of over/underflow. And where to set the limits? I think it might be a ratio of exponent range compared with total digits of the compound type...

A couple of thoughts we need to make here...

Cc: @sinandredemption and @cosurgi

**Comment by ckormanyos** [comment]
This has been tabled for the remainder of the GSoC21

Cc: @sinandredemption and @cosurgi
