### ISSUE TITLE
double_float move forward with formatted output streaming

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#9]

**Comment by sinandredemption** [comment]
Hello @ckormanyos @cosurgi 

Standard-compliant formatted output streaming is now almost complete. However, one minor inconvenience/problem remains. In rare cases, `cpp_double_float<float>` does not round the given number accurately to the required precision. For example, for the number `4.933775e+04`, using the std::ios::fixed flag and at a precision of 1, we have the following discrepancy:
expected: '49337.**8**' vs actual: '49337.**7**'

After extracting all the digits as done in [this loop](https://github.com/BoostGSoC21/multiprecision/blob/5da8f963477323fd2f0dcfc9b34b6fc9a5024a6c/include/boost/multiprecision/cpp_double_float.hpp#L677), `f_prime` _in theory_ should be exactly equal to **5** (since that is the last left digit), but in practice, a small error term is observed. My guess explanation is that the division performed on [line 658](https://github.com/BoostGSoC21/multiprecision/blob/5da8f963477323fd2f0dcfc9b34b6fc9a5024a6c/include/boost/multiprecision/cpp_double_float.hpp#L658) is not exact.

**Comment by ckormanyos** [comment]
Hi @sinandredemption thanks for moving forward on this.

I will look into the test case you mention. It seems like a probable edge case. The actual value of `std::numeric_limits<float>::digits10` is 6, whereas the `max_digits10` member for `float` is 9. So there is a lot going on in `float` beyond that final decimal digit. We can look at the exact way that particular `float` value is stored in binary representation and see if that is insightful.

Rounding and floating-point representation is something that is generally difficult and ultimately, we might need a little help if we can't crack this case. I'll take a look soon and report back.

**Comment by cosurgi** [comment]
> My guess explanation is that the division performed on line 658 is not exact.

At first I was thinking that maybe the division in that line

     auto f_prime = (f > FloatingPointType(0) ? f : -f) / cpp_double_float<FloatingPointType>::pow10(exp10);

happens between `FloatingPointType/cpp_double_float<FloatingPointType>` and the solution would be simple: just use a higher numerator precision `cpp_double_float<FloatingPointType>`. But this is not the case. Numerator appears to be `const cpp_double_float<FloatingPointType>& f`.

This however brings an extremely simple solution. We are doing `stringstream` conversions here, they are not supposed to be super fast. We could use `cpp_double_float<cpp_double_float<FloatingPointType>>` in the numerator and eliminate all problems altogether. This could work even without bringing in the dependency on `cpp_quad_float<FloatingPointType>` because by design we expect the `cpp_double_float<cpp_double_float<…>>` to work correctly if it is given itself as an argument.

**Comment by sinandredemption** [comment]
Hello @cosurgi 

Yes. That could be possible. The next thing I am going to work on is making sure, through robust testing, that the cascade construct `cpp_double_float<cpp_double_float<>>` works just as intended.

However, another possible solution could be to code a `fmod()` implementation for `cpp_double_float<>`, and extracting the whole number digits (the digits that appear before the decimal point) through repeated division and `fmod()`. This should, _intuitively_, solve the precision problem encountered while dividing by `pow10(exp10)` when `exp10` is very large.

Kind regards,
Fahad.

**Comment by cosurgi** [comment]
Yes, using integer part separately could also help. 

I just realized that this could be also related to the fact that in Table 3 and Table 4 in #21 the float has either 13 or 14 `digits10`.

**Comment by ckormanyos** [comment]
Finished with the backend requirements of #34
